Quiz_master/config/routes.rb
Rails.application.routes.draw do
  root 'questions#index'

  resources :questions

  get "quiz/index"
  post "quiz/start"
  get "quiz/question"
  post "quiz/question"
  post "quiz/answer"
  get "quiz/end"
  post "choices/create"
  post "choices/destroy"
end

Quiz_master/app/models/choice.rb
class Choice < ActiveRecord::Base
  belongs_to :question
end

Quiz_master/app/models/question.rb
class Question < ActiveRecord::Base
  has_many :choices

  def uncorrect
    choices.each {|c| c.correct = false}
  end

  def answer
    uncorrect
    choices.select {|c| c.correct}[0]
  end

  def answer= choice
    if !answer.nil?
      answer.correct = false
    end
    if choices.include? choice
      choice.correct = true
    else
      choices << choice
      choice.correct = true
    end
  end
end

Quiz_master/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

Quiz_master/app/controllers/concerns/choices_controller.rb
class ChoicesController < ApplicationController
  def create
    @question = Question.find(params[:question])
    text = params[:text]
    correct = params[:correct] == '1'
    new = Choice.create(:text => text, :correct => correct, :question_id => @question.id)

    if new.correct
      @question.answer = new
    end

    redirect_to question_path(@question)
  end

  def destroy
    @question = Question.find(params[:question])
    @choice = Choice.find(params[:choice])
    @choice.destroy

    redirect_to question_path(@question)
  end
end

Quiz_master/app/controllers/concerns/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @questions = Question.all
    @questions.sort {|a,b| a.text <=> b.text}

    respond_to do |format|
      format.html
      format.xml {render :xml => @questions}
    end
  end

  def show
    @question = Question.find(params[:id])
    respond_to do |format|
      format.html
      format.xml {render :xml => @question}
    end
  end

  def new
    @question = Question.new

    respond_to do |format|
      format.html
      format.xml {render :xml => @question}
    end
  end

  def edit
    @question = Question.find(params[:id])
  end

  def create
    @question = Question.new (params_question)

    respond_to do |format|
      if @question.save
        format.html {redirect_to(@question, :notice => 'Pregunta agregada exitosamente')}
        format.xml {render :xml => @question, :status => :created, :location => @question}
      else
        format.html {render :action => 'new'}
        format.xml {render :xml => @question.errors, :status => :unprocessable_entity}
      end
    end
  end

  def update
    @question = Question.find(params[:id])

    respond_to do |format|
      if @question.update_attributes(params_question)
        format.html {redirect_to(@question, :notice => 'Pregunta actualizada correctamente')}
        format.xml {head :ok}
      else
        format.html {render :action => 'edit'}
        format.xml {render :xml => @question.errors, :status => :unprocessable_entity}
      end
    end
  end

  def destroy
    @question = Question.find(params[:id])
    @question.destroy

    respond_to do |format|
      format.html {redirect_to(question_url)}
      format.xml {head :ok}
    end
  end

  private
  def params_question
    params.require(:question).permit(:text)
  end
end

Quiz_master/app/controllers/concerns/quiz_controller.rb
class QuizController < ApplicationController
  def index
  end

  def start
    total = params[:number].to_i
    all = Question.all.map {|x| x.id}
    session[:questions] = all.sort_by{rand}[0..(total-1)]
    session[:total] = total
    session[:current] = 0
    session[:correct] = 0
    redirect_to :action => 'question'
  end

  def question
    @current = session[:current]
    @total = session[:total]
    if @current >= @total
      redirect_to :action => 'end'
      return
    end
    @question = Question.find(session[:questions][@current])
    @choices = @question.choices.sort_by {rand}
    session[:question] = @question
    session[:choices] = @choices
  end

  def answer
    @current = session[:current]
    @total = session[:total]
    choiceid = params[:choice]
    @question = session[:question]
    @choices = session[:choices]
    @choice = choiceid ? Choice.find(choiceid):nil
    if @choice and @choice.correct == 1
      @correct = true
      session[:correct] += 1
    else
      @correct = false
    end
    session[:current] += 1
  end

  def end
    @correct = session[:correct]
    @total = session[:total]
    @score = @correct * 100 / @total
  end
end

Quiz_master/app/helpers/application_helper.rb
module ApplicationHelper
end

Quiz_master/app/helpers/choices_helper.rb
module ChoicesHelper
end

Quiz_master/app/helpers/questions_helper.rb
module QuestionsHelper
end

Quiz_master/app/helpers/quiz_helper.rb
module QuizHelper
end

Quiz_master/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>QuizD</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

Quiz_master/app/views/questions/_form.html.erb
<%= form_for(@question) do |f| %>
<% if @question.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@question.errors.count, 'error') %>
    prohibited this question from beign saved:
  </h2>
  <ul>
    <% @question.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
        <% end %>
  </ul>
</div>
<% end %>

<div class="field">
  <%= f.label :text %>
  <%= f.text_area :text, :size => '50x3' %>
</div>
<div class="actions">
  <%= f.submit :class => 'btn btn-success' %>
</div>
<% end %>

Quiz_master/app/views/questions/edit.html.erb
<h1>Edit Question</h1>
<%= render 'form' %><br/>
<%= link_to 'show', @question, :class => 'btn btn-primary' %>
<%= link_to 'Back', questions_path, :class => 'btn btn-warning' %>
<% content_for(:title) do %>
Edit question
<% end %>

Quiz_master/app/views/questions/index.html.erb
<h1>Questions...</h1>
<p>Total: <%= @questions.size %></p>
<p><%= link_to'New Question', new_question_path, :class => 'btn btn-primary' %></p>
<table class="table">
  <tr>
    <th>Pregunta</th>
    <th>Opciónes</th>
    <th colspan="3">Opciones</th>
  </tr>
  <% @questions.each do |question| %>
  <tr>
    <td><%= question.text %></td>
    <td>
      <ul>
        <% question.choices.each do |choice| %>
        <li>
          <%= choice.text %>
          <% if choice.correct == 1 %> (correct) <% end %>
        </li>
        <% end %>
      </ul>
    </td>
    <td><%= link_to 'show', question, :class => 'btn btn-info' %></td>
    <td><%= link_to 'Edit', edit_question_path(question), :class => 'btn btn-info' %></td>
    <td><%= link_to 'Destroy', question, :confirm => 'Estas seguro ?', :method => :delete, :class => 'btn btn-danger' %></td>
  </tr>
      <% end %>
</table>
<% content_for(:title) do %>
All questions
<% end %>
<%= link_to 'Realizar Quiz', quiz_index_url, :class => 'btn btn-success' %>

Quiz_master/app/views/questions/new.html.erb
<h1>New Question?</h1>
<%= render 'form' %><br/>

<%= link_to 'Back', questions_path, :class => 'btn btn-warning'%>
<% content_for(:title) do %>
New Question
<% end %>

Quiz_master/app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Text:</strong>
  <%= @question.text %>
</p>
<h4>Choices</h4>
<ul>
  <% @question.choices.find_each do |choice| %>
      <li>
        <%= choice.text %>
        <% if choice.correct == 1 %> (Correct) <% end %>
  <%= form_tag({:controller => 'choices', :action => 'destroy', :class => 'table'}) do %>
      <%= hidden_field_tag :question, @question.id %>
      <%= hidden_field_tag :choice, choice.id %>
      <%= submit_tag 'Delete', :class => 'btn btn-xs btn-danger' %>
  <% end %>
  </li>
  <% end %>
</ul>
<h5>New Chooice</h5>
<%= form_tag({:controller => 'choices', :action => 'create'}) do %>
    <%= hidden_field_tag :question, @question.id %>
    <%= label_tag :text, 'Text' %><br />
    <%= text_field_tag :text %><br />
    <%= check_box_tag :correct %><br />
    <br />
    <%= submit_tag 'create' %>
<% end %>
<%= link_to 'Edit', edit_question_path(@question), :class => 'btn btn-warning' %>
<%= link_to 'Back', questions_path, :class => 'btn btn-primary' %>
<% content_for(:title) do %>
    Questions Details
<%end%>